apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: taydinadnan/posts
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: posts-nodeport-srv1
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      port: 8001
      targetPort: 8001
      protocol: TCP
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: posts-nodeport-srv2
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      port: 8001
      targetPort: 8001
      protocol: TCP
